logins:
  server: <server>
  name: <your-username>
  password: <your-password>
logging:
  level: DEBUG
  filename: wurzelbot.log
tasks:
  - grow_for_quests:
    - CityQuest
    - ParkQuest
    - DecoGardenQuest
    - BeesGardenQuest
    - TreeQuest
  - grow_plants:
    - Karotte
    - Salat
  - farm_town_park
  - start_bees_tour
  - sell_to_wimps_percentage: 80
  - sell_on_marketplace: 100